import os
import shutil
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator, save_img

# ==========================================
# CONFIGURATIONS
# ==========================================
TARGET_SIZE = (224, 224)
BATCH_SIZE = 32
RANDOM_STATE = 42

def organize_dataset_from_metadata(metadata_path, image_dir, output_dir):
    """
    Reads HAM10000 metadata, splits into Train(80%)/Val(10%)/Test(10%), 
    and organizes copies of images into proper subdirectories by class.
    
    Assumes HAM10000 metadata has 'image_id' and 'dx' (disease class) columns.
    """
    print("--- Starting Dataset Organization ---")
    
    # 1. Load metadata
    if not os.path.exists(metadata_path):
        print(f"Error: Metadata file not found at {metadata_path}")
        return False
        
    df = pd.read_csv(metadata_path)
    
    # Ensure image mapping to exact extensions (e.g. .jpg)
    df['image_path'] = df['image_id'].apply(lambda x: os.path.join(image_dir, f"{x}.jpg"))
    
    # 2. Filter out missing images from dataframe
    df_exists = df[df['image_path'].apply(os.path.exists)].copy()
    if len(df_exists) == 0:
        print(f"Error: No actual images found in '{image_dir}'. Check paths.")
        return False
        
    classes = df_exists['dx'].unique()
    print(f"Detected {len(classes)} disease classes: {classes}")

    # 3. Stratified Train/Val/Test Split (80/10/10)
    try:
        # Split 80% Train, 20% Temporary (for val/test)
        train_df, temp_df = train_test_split(
            df_exists, test_size=0.20, random_state=RANDOM_STATE, stratify=df_exists['dx']
        )
        # Split 20% Temporary into 10% Validation, 10% Test
        val_df, test_df = train_test_split(
            temp_df, test_size=0.50, random_state=RANDOM_STATE, stratify=temp_df['dx']
        )
    except ValueError as e:
        print(f"Warning during stratification, falling back to random split: {e}")
        train_df, temp_df = train_test_split(df_exists, test_size=0.20, random_state=RANDOM_STATE)
        val_df, test_df = train_test_split(temp_df, test_size=0.50, random_state=RANDOM_STATE)

    partitions = {
        'train': train_df,
        'validation': val_df,
        'test': test_df
    }

    # 4. Create folder structure (train/class_name) and copy images
    for split_name, split_df in partitions.items():
        for cls in classes:
            folder_path = os.path.join(output_dir, split_name, cls)
            os.makedirs(folder_path, exist_ok=True)
            
            # Fetch all image paths for this specific split and class
            cls_images = split_df[split_df['dx'] == cls]['image_path']
            for img_path in cls_images:
                filename = os.path.basename(img_path)
                dest_path = os.path.join(folder_path, filename)
                
                # Copy file to new structured directory
                if not os.path.exists(dest_path):
                    shutil.copy2(img_path, dest_path)
                    
        print(f"Organized {len(split_df)} images into '{split_name}/' directory.")

    print(f"Dataset successfully organized at: {output_dir}")
    return True


def get_data_generators(dataset_dir):
    """
    Sets up TensorFlow/Keras ImageDataGenerators for train, validation, and test.
    Applies predefined augmentations to train limits overfitting.
    """
    print("\n--- Initializing Data Generators ---")
    
    train_dir = os.path.join(dataset_dir, 'train')
    val_dir = os.path.join(dataset_dir, 'validation')
    test_dir = os.path.join(dataset_dir, 'test')
    
    if not os.path.exists(train_dir):
        print(f"Setup Error: Training directory missing at {train_dir}")
        return None, None, None

    # 1. Training Generator (Normalization + Data Augmentation)
    train_datagen = ImageDataGenerator(
        rescale=1./255,               # Normalization: scale pixel values 0-1
        rotation_range=20,            # Augmentation: Rotate up to 20 degrees
        horizontal_flip=True,         # Augmentation: Random horizontal flip
        zoom_range=0.2,               # Augmentation: Zoom in/out by 20%
        brightness_range=[0.8, 1.2],  # Augmentation: Darken/lighten randomly
        fill_mode='nearest'           # Handle empty pixels generated by transforms
    )

    # 2. Validation & Test Generator (ONLY Normalization. NO Augmentation applied here!)
    val_test_datagen = ImageDataGenerator(
        rescale=1./255
    )

    # 3. Load Images directly from directories in batches
    train_generator = train_datagen.flow_from_directory(
        directory=train_dir,
        target_size=TARGET_SIZE,
        batch_size=BATCH_SIZE,
        class_mode='categorical',     # Multi-class output (One-hot encoded)
        shuffle=True                  # Shuffle training data
    )

    val_generator = val_test_datagen.flow_from_directory(
        directory=val_dir,
        target_size=TARGET_SIZE,
        batch_size=BATCH_SIZE,
        class_mode='categorical',
        shuffle=False                 # Sequential ordering for evaluation
    )

    test_generator = val_test_datagen.flow_from_directory(
        directory=test_dir,
        target_size=TARGET_SIZE,
        batch_size=BATCH_SIZE,
        class_mode='categorical',
        shuffle=False                 # Sequential ordering for strict evals
    )

    return train_generator, val_generator, test_generator


if __name__ == "__main__":
    # ==========================================
    # DEMONSTRATION AND TESTING BLOCK
    # ==========================================
    # Define relative paths. User should update these based on where the HAM10000 data resides.
    WORKSPACE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    RAW_METADATA_CSV = os.path.join(WORKSPACE_DIR, "data", "raw", "HAM10000_metadata.csv")
    RAW_IMAGES_DIR = os.path.join(WORKSPACE_DIR, "data", "raw", "images")
    STRUCTURED_DATASET_DIR = os.path.join(WORKSPACE_DIR, "data", "structured_dataset")
    
    print(f"Working Directory Base: {WORKSPACE_DIR}")

    # RULE INTERVENTION FOR DEMO:
    # If the user has just downloaded everything but has not structured it, uncomment below:
    # organize_dataset_from_metadata(RAW_METADATA_CSV, RAW_IMAGES_DIR, STRUCTURED_DATASET_DIR)
    
    # -------------------------------------------------------------
    # FAKE DATA GENERATION FOR SCRIPT VALIDATION (Can be removed)
    # Creates empty structured folders with a dummy image so code works out-of-the-box
    # -------------------------------------------------------------
    if not os.path.exists(STRUCTURED_DATASET_DIR):
        print("Note: Creating mock dataset folders and dummy images to validate the pipeline...")
        dx_classes = ['akiec', 'bcc', 'bkl', 'df', 'mel', 'nv', 'vasc']
        for split in ['train', 'validation', 'test']:
            os.makedirs(os.path.join(STRUCTURED_DATASET_DIR, split), exist_ok=True)
            for cls in dx_classes:
                cls_dir = os.path.join(STRUCTURED_DATASET_DIR, split, cls)
                os.makedirs(cls_dir, exist_ok=True)
                # Create one fake 224x224 RGB image
                img_array = np.zeros((224, 224, 3), dtype=np.uint8)
                save_img(os.path.join(cls_dir, 'dummy_1.jpg'), img_array)

    # -------------------------------------------------------------
    # PIPELINE EXECUTION
    # -------------------------------------------------------------
    train_gen, val_gen, test_gen = get_data_generators(STRUCTURED_DATASET_DIR)
    
    # Verify outputs
    if train_gen:
        print("\n--- Verification: Generator & Batch Details ---")
        
        # Extract mapping of classes generated by keras
        class_indices = train_gen.class_indices
        print(f"Class Mapping Discovered: \n{class_indices}")
        
        # Grab a single batch from the iterator
        images, labels = next(train_gen)
        
        print("\n--- Technical Batch Analysis ---")
        print(f"Batch Items Generated: {len(images)} images")
        print(f"Image Batch Shape: {images.shape} -> (batch_size, height, width, channels)")
        print(f"Label Batch Shape: {labels.shape} -> (batch_size, number_of_classes)")
        
        # Ensure scaling logic worked
        print(f"Target size successfully matched: {images.shape[1]}x{images.shape[2]}")
        print(f"Max Pixel Value in batch: {np.max(images):.2f} (Expected <= 1.0 due to 1/255 rescale)")
        print(f"Min Pixel Value in batch: {np.min(images):.2f} (Expected >= 0.0)")
        
        print("\nSUCCESS: Dataset pipeline correctly structured and ready for model training!")
